### ISSUE TITLE
Undeclared dependency Test::MockModule

### ISSUE THREAD

**Issue by eserte** [Altreus/p5-Test-Ratchet#4]
It seems that Test::MockModule is required for the test suite to pass, but it is not declared as a dependency (or maybe in such a way that CPAN.pm does not understand it):
```
Can't locate Test/MockModule.pm in @INC (you may need to install the Test::MockModule module) (@INC contains: ... .) at t/clank.t line 9.
BEGIN failed--compilation aborted at t/clank.t line 9.
t/clank.t .............. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by Altreus** [comment]
Thanks! This is in master, will release soon if there's nothing else to do :)
